# Copyright 2026 Rinat Ishmaev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Сборка финального техзадания (ТЗ §6)."""

from typing import Any

from app.config import ComplexityLevel


def build_assignment_markdown(
    project_name: str,
    feasibility_score: float,
    complexity_level: ComplexityLevel,
    selected_stack: dict[str, Any],
    implementation_steps: str,
    cost_section: str,
    modified_options: list[dict[str, Any]],
) -> str:
    """Формирует standalone .md для Cursor/Claude Code."""
    options_block = ""
    if modified_options:
        options_block = "\n### Alternative Scope Options (FI < 0.7)\n"
        for i, opt in enumerate(modified_options, 1):
            options_block += (
                f"\n{i}. **{opt.get('title', 'Option')}**\n"
                f"   - Scope: {opt.get('scope', '')}\n"
                f"   - Tradeoffs: {opt.get('tradeoffs', '')}\n"
            )

    stack_lines = "\n".join(
        f"* **{k}:** {v}" for k, v in selected_stack.items()
    )

    return f"""# Technical Assignment: {project_name}
## Status: Evaluated & Validated (Feasibility: {feasibility_score:.2f})

### 1. Technology Stack Configuration
{stack_lines}

### 2. Step-by-Step Implementation Protocol
- [ ] **Step 1: Guardrail Setup.** Deploy data masking filters to ensure safety rules are not breached.
- [ ] **Step 2: Core Route Implementation.** Build API wrappers supporting Prompt Caching features.
- [ ] **Step 3: Verification Suites.** Setup unit tests for edge-case monitoring.
{implementation_steps}

### 3. Context Rules (.cursorrules Snippet)
```json
{{
  "rules": [
    "Always check current complexity level prior to calling cloud APIs.",
    "Strip user logs of any credentials, tokens, or personal identifiers.",
    "Prioritize local inference pipelines for sensitive data structures."
  ]
}}
```

{cost_section}
{options_block}
---
*Generated by MATFES*
"""
